### ISSUE TITLE
Automatically move poison messages to another queue

### ISSUE THREAD

**Issue by ehsaanwelcome** [Jericho/Picton.Messaging#17]
Let me say, this is good work.

Is there any way to avoid message deletion in case of exception in the OnMessage block.
I have set the dequeue count to 3 and raised the exception in OnMessage block.
Message gets delete from the queue but it should not.
Any way to achieve above mentioned scenario?

I tested without using this library and non deleted message reappear to process until deleted.

**Comment by Jericho** [comment]
Thank you for the compliment. I’m looking forward to your comments and questions to improve Pictor even further. 

Regarding your questions: you’re correct that Picton deletes messages that fail to be processed after a certain number of tries. These are called “poison“ messages and the assumption is that they will continue to fail even if you retry. Of course you could increase the number of tries if you feel that your messages may successfully get processed on the 4th or 5th try. 

However it is generally advised to move poison messages to a different queue so they don’t clog your main queue and you don’t waste any time retrying to process messages that are likely to fail again. You can specify the ‘OnError’ handler where you can log the exception to help you understand why the message is failing and also to copy the message to a different queue. When messages are moved to a different queue (which is typically called the “poison” queue) you are responsible for implementing logic for figuring out why a given message has failed so many times and resolve the problem. 

Having said that, let me know what your scenario is and if it’s compelling we could discuss adding an option to prevent auto-deleting poison messages.

**Comment by Jericho** [comment]
I have been thinking about this scenario and I think the better way to handle would be for Picton to automatically  move the message to a "poison" queue after we exceed the maximum number of tries. What do you think?

**Comment by Jericho** [comment]
I am releasing an update that allows you to specify the name of a queue where poison messages are automatically moved. If you leave the name of this queue empty, the messages are simply deleted from the original queue and you are responsible for handling poison messages.
